IO.puts "~C A character list with no escaping or interpolation"
IO.puts "~c A character list, escaped and interpolated just like a single-quoted string ~R A regular expression with no escaping or interpolation"
IO.puts "~r A regular expression, escaped and interpolated"
IO.puts "~S A string with no escaping or interpolation"
IO.puts "~s A string, escaped and interpolated just like a double-quoted string"
IO.puts "~W A list of whitespace-delimited words, with no escaping or interpolation ~w A list of whitespace-delimited words, with escaping and interpolation"
